### ISSUE TITLE
Anaconda 3 Python Version 3.7 problem

### ISSUE THREAD

**Issue by Hassan313** [JoeyDelp/JoSIM#21]
Dear Joey,

I have a problem which is the Anaconda 3 Python 3.7. When I try to compile it is give me the below error.

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1181	cannot open input file 'python36.lib'	JoSIM	C:\JoSIM-master\src\josim_vs\LINK	1
Can you kindly advise how to fix this issue?

Thank you.

Best Regards
Hassan

**Comment by Hassan313** [comment]
Even if I go with the Python 3.6 version, I get the following error message:
![pythondll problem](https://user-images.githubusercontent.com/17442194/46750945-11172b00-cc6e-11e8-9d7e-b6c1229c77e8.png)

**Comment by JoeyDelp** [comment]
Good afternoon,

Did you set the environment variables as stated under the Windows 10 section of the[ReadMe.md](https://github.com/JoeyDelp/JoSIM/blob/master/README.md)?

These environment variables in Windows tell the system where to find the python36.lib.

Hope this helps

**Comment by Hassan313** [comment]
Dear Joey,


Yes. I did. 

Is your software compatible with the **Python 3.7**?

Thank you.

Best Regards
Hassan

**Comment by JoeyDelp** [comment]
Good day, it should be, simply edit the Linker settings inside project settings of Visual Studio under Input->Additional Dependencies.

Change python36.lib to python37.lib which should fix the issue. Once compiled it should work on any python version that is installed on the system.

Kind regards

**Comment by Hassan313** [comment]
Dear Joey, 

Good Evening,

Thank you for the information.

Best Regards
Hassan
