### ISSUE TITLE
Python 3.6 DLL Files Missing

### ISSUE THREAD

**Issue by Hassan313** [JoeyDelp/JoSIM#22]
Dear Joey, 

When I tried the Python 3.6 version, the below problem appeared: 
![pythondll problem](https://user-images.githubusercontent.com/17442194/46754525-8804f180-cc77-11e8-8a05-e487816b9143.png)

**Comment by Hassan313** [comment]
I downloaded the Python 3.6 DLL file from the below website 

https://www.dll-files.com/python36.dll.html


and added the DLL file to the bin folder where the executable files are, the above problem disappeared, however the below problem appeared:



![image](https://user-images.githubusercontent.com/17442194/46754812-40cb3080-cc78-11e8-8727-93c5f790ef8b.png)


It is saying that "ImportError: numpy.core.multiarray failed to import".

Please kindly help me with this issue.

Best Regards
Hassan

**Comment by Hassan313** [comment]
Dear Joey,

Thank you for your response.

I have followed as you have said in this email. It did not work. The problem was I had to add the Anaconda3 directory to the path variable of system.

Thank you.

Best Regards
Hassan

**Comment by JoeyDelp** [comment]
My apologies, it might be necessary to add the %PYTHONHOME% to the PATH variable as well. This however has not been necessary on some systems. I will update the readme to include this.

**Comment by Hassan313** [comment]
Dear Joey,

Thank you.

Best Regards
Hassan
