### ISSUE TITLE
SQUID simulation

### ISSUE THREAD

**Issue by anadb** [JoeyDelp/JoSIM#59]
Is it possible to model a SQUID in JoSIM?

In particular how to introduce the externally applied magnetic field?

**Comment by JoeyDelp** [comment]
Hi, yes ofcourse. Please see the following papers for ways to do this.

C. J. Fourie and K. Jackman, "Software Tools for Flux Trapping and Magnetic Field Analysis in Superconducting Circuits," in IEEE Transactions on Applied Superconductivity, vol. 29, no. 5, pp. 1-4, Aug. 2019, Art no. 1301004, doi: 10.1109/TASC.2019.2899333.

C. J. Fourie and K. Jackman, "Experimental Verification of Moat Design and Flux Trapping Analysis," in IEEE Transactions on Applied Superconductivity, vol. 31, no. 5, pp. 1-7, Aug. 2021, Art no. 1300507, doi: 10.1109/TASC.2021.3051582.

**Comment by anadb** [comment]
thank you
