### ISSUE TITLE
Question about AREA of junction.

### ISSUE THREAD

**Issue by Mengfei-Zhao** [JoeyDelp/JoSIM#79]
Dear Joey,

Thank you for making josim. I don't quite understand what AREA means when using junction. Consider the following netlist statement.

```
.model jjmit jj(rtype=1, vg=2.8mV, cap=0.07pF, r0=160, rn=16, icrit=0.1mA)
B1 node1 node2 jjmit area=1.5
```

I know that AREA is a modifier of **icrit**, which means $Ic_{jj}=area \cdot icrit$. But is AREA just a modifier of **icrit**? what about **cap, r0** and **rn**? Is AREA still a modifier of **cap, r0** and **rn**? That is to say $Cap_{jj}=area \cdot cap, \quad r0_{jj}=area \cdot r0_{model}, \quad rn_{jj}=area \cdot rn_{model}$. 

Thank you.

Best Regards

Mengfei Zhao

**Comment by JoeyDelp** [comment]
Hi Mengfei,

Area is purely a scaler value of that scales the model for the junction instance. Yes, it affects all those values.

Please see the model.cpp source file for a detailed view on what the area parameter alters.

Best regards,
Joey

**Comment by Mengfei-Zhao** [comment]
![image](https://user-images.githubusercontent.com/58592885/186810958-a852e7e0-be6e-46d7-8355-1835312482b8.png)

**Comment by JoeyDelp** [comment]
Yes that is correct. My apologies, I meant to say _jj.cpp_, but was answering from my phone since I was AFK.

**Comment by Mengfei-Zhao** [comment]
> Yes that is correct. My apologies, I meant to say _jj.cpp_, but was answering from my phone since I was AFK.

That's ok. Thank you very much. I suggest you can mention the detailed information about AREA in your Documentation.

**Comment by JoeyDelp** [comment]
Thank you for the suggestion, I will update the documentation accordingly
