### ISSUE TITLE
Slow CUS waveform handling

### ISSUE THREAD

**Issue by CeesWolfs** [JoeyDelp/JoSIM#96]
Hi! When profiling JoSim on Windows I found that it was spending a lot of time (over 2/3 in my case) in return_cus. Furthermore, I also found the runtime to scale quadratically with the simulation time. After some experimenting I believe I boiled it down to the following loop:
https://github.com/JoeyDelp/JoSIM/blob/3b47f151b2caba86d372077e13ca879db7e93ddb/src/Function.cpp#L390-L394

 Which is looping over all indexes to find which one the current time belongs to. I think it could be replaced by the following:
`
int idx = static_cast<int>(norm_x / ts);
if (idx >= ampValues_.size()) idx = ampValues_.size() - 1;
`
Which is much faster and avoids the quadratic scaling. I think GCC is smart enough to optimize this away but MSVC is not so I still think it is worth changing.

**Comment by JoeyDelp** [comment]
Thanks for spotting this! I have incorporated your suggestion and updated JoSIM to v2.6.10.
